<?php
/**
 * SettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Nightscout API
 *
 * Own your DData with the Nightscout API
 *
 * OpenAPI spec version: 0.8.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * SettingsTest Class Doc Comment
 *
 * @category    Class */
// * @description Settings
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache License v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SettingsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "Settings"
     */
    public function testSettings()
    {

    }

    /**
     * Test attribute "units"
     */
    public function testPropertyUnits()
    {

    }

    /**
     * Test attribute "time_format"
     */
    public function testPropertyTimeFormat()
    {

    }

    /**
     * Test attribute "custom_title"
     */
    public function testPropertyCustomTitle()
    {

    }

    /**
     * Test attribute "night_mode"
     */
    public function testPropertyNightMode()
    {

    }

    /**
     * Test attribute "theme"
     */
    public function testPropertyTheme()
    {

    }

    /**
     * Test attribute "language"
     */
    public function testPropertyLanguage()
    {

    }

    /**
     * Test attribute "show_plugins"
     */
    public function testPropertyShowPlugins()
    {

    }

    /**
     * Test attribute "show_rawbg"
     */
    public function testPropertyShowRawbg()
    {

    }

    /**
     * Test attribute "alarm_types"
     */
    public function testPropertyAlarmTypes()
    {

    }

    /**
     * Test attribute "alarm_urgent_high"
     */
    public function testPropertyAlarmUrgentHigh()
    {

    }

    /**
     * Test attribute "alarm_high"
     */
    public function testPropertyAlarmHigh()
    {

    }

    /**
     * Test attribute "alarm_low"
     */
    public function testPropertyAlarmLow()
    {

    }

    /**
     * Test attribute "alarm_urgent_low"
     */
    public function testPropertyAlarmUrgentLow()
    {

    }

    /**
     * Test attribute "alarm_timeago_warn"
     */
    public function testPropertyAlarmTimeagoWarn()
    {

    }

    /**
     * Test attribute "alarm_timeago_warn_mins"
     */
    public function testPropertyAlarmTimeagoWarnMins()
    {

    }

    /**
     * Test attribute "alarm_timeago_urgent"
     */
    public function testPropertyAlarmTimeagoUrgent()
    {

    }

    /**
     * Test attribute "alarm_timeago_urgent_mins"
     */
    public function testPropertyAlarmTimeagoUrgentMins()
    {

    }

    /**
     * Test attribute "enable"
     */
    public function testPropertyEnable()
    {

    }

    /**
     * Test attribute "thresholds"
     */
    public function testPropertyThresholds()
    {

    }

}
